### ISSUE TITLE
Regression in 4.0.0: `ISO3166::Country.translations(:en)` with symbol arg raises

### ISSUE THREAD

**Issue by henrik** [countries/countries#691]
Hi!

This worked fine in 3.1.0:

```
>> ISO3166::Country.translations(:sv)
=> {"AW"=>"Aruba",
 "AF"=>"Afghanistan",
…
```

But in 4.0.0, it raises if the locale isn't a string:

```
>> ISO3166::Country.translations(:sv)
NoMethodError: undefined method `sub' for :sv:Symbol

>> ISO3166::Country.translations("sv")
=> {"AW"=>"Aruba",
 "AF"=>"Afghanistan",
```

This broke code in our app that passed in a symbol. I assume this is not an intended API change?

**Comment by henrik** [comment]
Hi @pmor! Just thought I'd bump this and check if you're open to changing this back, or if this is an intended API change.

**Comment by espen** [comment]
`ISO3166::Country.translations(:sv)` works for me. Is there anything that could affect this?

**Comment by pmor** [comment]
@henrik What version of ruby, and what other gems are you using?

**Comment by pmor** [comment]
Actually, I believe I tracked down the issue. @henrik Do you have any custom countries defined? Or other custom data?

Digging into the docs, using symbols doesn't seem to have been "officially" supported, since all the documentation uses strings. Even so, it is a regression from 3.x, so I'll be pushing a fix later today

**Comment by pmor** [comment]
Releasing fix in 4.0.1 in a bit.

**Comment by henrik** [comment]
Yes, we do have custom countries and modified country data. Thank you! Will try out 4.0.1 tomorrow.
